# Generated by Django 3.2.3 on 2021-05-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
