# Generated by Django 3.2.3 on 2021-08-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0004_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=100)),
                ('complete', models.BooleanField(null=True)),
                ('progress_epoch', models.IntegerField(null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='upload',
            name='files',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
