# Generated by Django 3.2.3 on 2021-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0005_auto_20210809_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='start_time',
        ),
        migrations.AddField(
            model_name='train',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
