# Generated by Django 3.2.3 on 2021-08-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0007_alter_train_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
