# Generated by Django 3.2.3 on 2021-08-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0008_alter_train_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
