# Generated by Django 3.2.3 on 2021-10-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catch', '0010_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='file_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='progress_batch',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='test_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='train_accuracy',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='train_port',
            field=models.IntegerField(null=True),
        ),
    ]
